# SPDX-License-Identifier: MIT

[tool.ruff]
target-version = "py38"
line-length = 120

[tool.ruff.lint]
ignore = ["F403", "F405"]

[tool.ruff.per-file-ignores]
"mcsrvstat/__init__.py" = ["F401"]

[tool.ruff.format]
quote-style = "single"
